## Numpy basics notes from book Python for Data Analysis
To get a detailed notes an tutorial please read this book and refer to https://github.com/wesm/pydata-book

In [1]:
# Use SHIFT-ENTER to run each cell.
# CTRL-s to save 
# Enter to edit the cell
import numpy as np

In [2]:
# Generate a random array of 2row and 3 cols. 
# First number always represents row and second column.
my_arr = np.random.randn(2,3)
my_arr


array([[-0.4268255 ,  1.37933539, -1.09817801],
       [-0.73901613, -0.49430412, -1.23102969]])

In [3]:
# Multiple array by 10
my_arr * 10

array([[ -4.26825505,  13.79335395, -10.98178012],
       [ -7.39016129,  -4.94304125, -12.3102969 ]])

In [4]:
# Do elementwise add
my_array = np.array([[1,1,1],[2,2,2]])
my_array + my_array

array([[2, 2, 2],
       [4, 4, 4]])

In [5]:
# Get the shape of an array. 
# first number is row, second is column
my_array.shape

(2, 3)

In [6]:
#create a numpy array with python list
data1 = [1,2.5,9]
arr1 = np.array(data1)
arr1

array([1. , 2.5, 9. ])

In [7]:
# Create a 3x6 array with zeros.
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
# Create a 3x6 array with that is uninitialized
np.empty((3,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
# Create a 1x2 array of floats.
arr1 = np.array([1,2.0],dtype=np.float64)
arr1

array([1., 2.])

In [10]:
# Create a 1x2 array of ints.
arr2 = np.array([1,2.0],dtype=np.int32)
arr2

array([1, 2])

In [11]:
# Convert float array to int array
arr = np.array([1.2,1.3,1.5,1.9])
arr = arr.astype(np.int32)
arr

array([1, 1, 1, 1])

In [12]:
# Do a elementwise multiplication of two arrays.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [13]:
# Do a dot product of two arrays.
arr = np.array([[1,2],[4,5]])
np.dot(arr,arr)
# [1 2] x [1 2]
# [4 5]   [4 5]

# [ (1*1 + 2*4)  (1*2 + 2*5) ]
# [ (4*1 + 5*4)  (4*2 + 5*5) ]
#

array([[ 9, 12],
       [24, 33]])

In [14]:
## Generate random array of 10 integers.
arr = np.arange(10)

print(f'print array {arr}')
print(f'first 5 elems arr[:5] =>  {arr[:5]}')
print(f'last  5 elems arr[-5:] => {arr[-5:]}')
# Not start index is included, but stop index is excluded
print(f'elems from 3 to 7 elems arr[3:8] => {arr[3:8]}')

# Add 12 from index 5 to 7 , this is known as broadcasting
arr[5:8] = 12
print(f'Add 12 from index 5 to 7 arr[5:8]=12 => {arr}')

# Replace all the elems 
arr[:] = 64
print(f'Replace all elems with 63 arr[:]=64 => {arr}')

print array [0 1 2 3 4 5 6 7 8 9]
first 5 elems arr[:5] =>  [0 1 2 3 4]
last  5 elems arr[-5:] => [5 6 7 8 9]
elems from 3 to 7 elems arr[3:8] => [3 4 5 6 7]
Add 12 from index 5 to 7 arr[5:8]=12 => [ 0  1  2  3  4 12 12 12  8  9]
Replace all elems with 63 arr[:]=64 => [64 64 64 64 64 64 64 64 64 64]


In [15]:
arr = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]])

print(f'select first two rows and first two cols \n{arr[:2,:2]}')
print(f'start 1st row and end at 1st row,and select 1st two cols\n{arr[1,:2]}')
print(f'get all the rows :, and start at 0th col and end at 1th col \n{arr[:,:2]}')

select first two rows and first two cols 
[[1 2]
 [4 5]]
start 1st row and end at 1st row,and select 1st two cols
[4 5]
get all the rows :, and start at 0th col and end at 1th col 
[[1 2]
 [4 5]
 [7 8]]


In [16]:
# reshape an array.
# Create a array of 15 elements
arr = np.arange(15)
# Reshape it to 3x5 array
arr.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
# Get the maximum elements from two arrays.
arr_x = np.array([1,4,23,55])
arr_y = np.array([4,11,3,45])
np.maximum(arr_x,arr_y)                

array([ 4, 11, 23, 55])

In [18]:
# Get unique elements from an array
names = np.array(['zat','bat','rat','zat','rat'])
np.unique(names)

array(['bat', 'rat', 'zat'], dtype='<U3')

In [19]:
# Do a cumulative sum of of elements of the array.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Output is a single dimentional array flattened out.
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)