   # Pytorch basics
   This tutorial is based on https://github.com/yunjey/pytorch-tutorial

In [7]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms
torch.version

<module 'torch.version' from 'C:\\Users\\Samsung\\Anaconda3\\envs\\fastai\\lib\\site-packages\\torch\\version.py'>

In [13]:
# create a basic rank 1 tensor
x = torch.tensor([1.0], requires_grad=True)
print(x.size())
x = torch.randn(4,4)
print(x)
# flatten x
x = x.view(-1,16)
print(x)

torch.Size([1])
tensor([[ 0.5786,  2.3931, -0.4230,  0.1488],
        [-1.2989, -0.3657,  0.3460, -0.8806],
        [-0.9821,  1.3491,  0.0681, -0.9863],
        [ 1.3468, -0.4600,  0.6631, -1.0717]])
tensor([[ 0.5786,  2.3931, -0.4230,  0.1488, -1.2989, -0.3657,  0.3460, -0.8806,
         -0.9821,  1.3491,  0.0681, -0.9863,  1.3468, -0.4600,  0.6631, -1.0717]])


# Basic autograd example 1            

In [6]:
# Create tensors.

x = torch.tensor(1.0, requires_grad=True)
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)

# Build a computational graph.
y = w * x + b    # y = 2 * x + 3
# Compute gradients.
y.backward()

# Print out the gradients.
print(f'First run x = {x.grad}')    # x.grad = 4
print(f'First run w = {w.grad}')    # w.grad = 1 
print(f'First run b = {b.grad}')    # b.grad = 1 

# Build a computational graph.
y = w * x + b    # y = 2 * x + 3
# Compute gradients.
y.backward()
print(f'Second run x = {x.grad}')    # x.grad = 4
print(f'Second run w = {w.grad}')    # w.grad = 1 
print(f'Second run b = {b.grad}')    # b.grad = 1 

# Clear the grads manually.
x.grad.data.zero_()
w.grad.data.zero_()
b.grad.data.zero_()

# Build a computational graph.
y = w * x + b    # y = 2 * x + 3
# Compute gradients.
y.backward()
print(f'Third run x = {x.grad}')    # x.grad = 4
print(f'Third run w = {w.grad}')    # w.grad = 1 
print(f'Third run b = {b.grad}')    # b.grad = 1 


First run x = 2.0
First run w = 1.0
First run b = 1.0
Second run x = 4.0
Second run w = 2.0
Second run b = 2.0
Third run x = 2.0
Third run w = 1.0
Third run b = 1.0


# Basic autograd example 2 

In [14]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)
print(f'x={x.shape}')
print(f'y={y.shape}')

x=torch.Size([10, 3])
y=torch.Size([10, 2])


In [16]:
# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.2696,  0.1097, -0.0469],
        [-0.1439, -0.0599, -0.1614]], requires_grad=True)
b:  Parameter containing:
tensor([-0.4313, -0.0888], requires_grad=True)


In [ ]:
# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [ ]:
# Forward pass.
for i in range(0,10,1):
    pred = linear(x)
    # Compute loss.
    loss = criterion(pred, y)
    print('loss: ', loss.item())
    # Backward pass.
    loss.backward()
    # Print out the gradients.
    print ('dL/dw: ', linear.weight.grad) 
    print ('dL/db: ', linear.bias.grad)
    # 1-step gradient descent.
    optimizer.step()
    # You can also perform gradient descent at the low level.
    # linear.weight.data.sub_(0.01 * linear.weight.grad.data)
    # linear.bias.data.sub_(0.01 * linear.bias.grad.data)
    

# Loading data from numpy    

In [17]:
# Create a numpy array.
x = np.array([[1, 2], [3, 4]])

# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)

# Convert the torch tensor to a numpy array.
z = y.numpy()